#!/bin/sh

# † Scientia es lux principium✨ ™

# Copyright © 2020 Luxcium (Benjamin Vincent Kasapoglu)

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# « †Scientia es lux principium✨ » IS A TRADEMARK OF BENJAMIN VINCENT KASAPOGLU
# (™ & © 2016-2020 ALL RIGHT RESERVED)

__SAVE_PREV_VERSION_INFO__=VERSION
VERSION="0.0.2"

# Help
# ==============================================================================≈
Help() {
  # Display Help
  echo "Loop through each sub-directory excluding dot-directory in a directory."
  echo
  echo "Syntax: fordirdo [-H|h|L|l|V|v] [<before>|<after>|<justBefore>|<justAfter>]"
  echo
  echo "options:"
  echo "-H or -h      Print this Help."
  echo "-L or -l      Print the MIT license notification."
  echo "-V or -v      Print software version (v${VERSION}) and exit."
  echo
  echo "Will produce a string and evaluate it with the ITEM placed in the middle"
  echo "BEFORE__JUSTBEFORE-ITEM-JUSTAFTER__AFTER"
  echo "Where '__' represent a blank space and '-' represent no space at all"
  echo "use empty string to bypass i.e. \"\" or \'\' if you need to skip to next"
  echo
  echo "You can use \$ITEM or \$DIR to represenmt the currently iterated Directory name"
  echo
  echo "before       Command will be placed before folowed by a space."
  echo "after        Command will be placed after preceded by a space."
  echo "justBefore   Command will be placed directly before whitout space."
  echo "justAfter    Command will be placed directly after whitout space."
  echo
  echo -e '\e[31m†Scientia es lux principium✨ ™\e[37m'
  echo

}

License() {
  # Display License
  echo
  echo
  echo -e '\e[31m†Scientia es lux principium✨ ™\e[37m'
  echo
  echo -e "\e[37;1m\e[1mCopyright © 2020 Luxcium (Benjamin Vincent Kasapoglu)"
  echo -e "\e[22m\e[37m"
  echo "Permission is hereby granted, free of charge, to any person obtaining a copy"
  echo "of this software and associated documentation files (the \"Software\"), to deal"
  echo "in the Software without restriction, including without limitation the rights"
  echo "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"
  echo "copies of the Software, and to permit persons to whom the Software is"
  echo "furnished to do so, subject to the following conditions:"
  echo
  echo "The above copyright notice and this permission notice shall be included in"
  echo "all copies or substantial portions of the Software."
  echo
  echo -e "\e[37;1m\e[1mTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"
  echo "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"
  echo "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"
  echo "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"
  echo "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"
  echo "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"
  echo "SOFTWARE."
  echo -e "\e[22m\e[37m"
  echo "« †Scientia es lux principium✨ » IS A TRADEMARK OF BENJAMIN VINCENT KASAPOGLU"
  echo "(™ & © 2016-2020 ALL RIGHT RESERVED)"
  echo
  echo -e '\e[0m'

}

Version() {
  # Display License
  echo "v${VERSION}"
  echo
  echo -e '\e[31m†Scientia es lux principium✨ ™\e[37m'
}

# Main program                                                                 #
# ==============================================================================≈

# Process the input options. Add options as needed.                            #
# ==============================================================================≈
# Get the options

while getopts ":hHvVlL" option; do
  case $option in
  h | H) # display Help
    Help
    exit
    ;;

  v | V) # Version
    Version
    exit
    ;;

  l | L) # License
    License
    exit
    ;;

  \?) # incorrect option
    echo "Error: Invalid option"
    exit 1
    ;;
  esac
done

unset -f Help
unset -f License
unset -f Version

for d in *; do
  __SAVE_PREV_ITEM__=ITEM
  __SAVE_PREV_DIR__=DIR
  ITEM=d
  DIR=d
  [ -d "${d}" ] && eval "${1:-'echo'} ${3}${d}${4} ${2}"
  ITEM=__SAVE_PREV_ITEM__
  DIR=__SAVE_PREV_DIR__
  unset -v __SAVE_PREV_ITEM__
  unset -v __SAVE_PREV_DIR__
  # unset -v d
done

VERSION=__SAVE_PREV_VERSION_INFO__
unset -v __SAVE_PREV_VERSION_INFO__

exit 0
