/*



  'activityBar.activeBackground': '#77116688',
  'activityBar.activeBorder': '#771166',
  'activityBar.activeFocusBorder': '#88bb33',
  'activityBar.background': '#1c1c30',
  'activityBar.background': dark16,  '#1c1c30',
  'activityBar.border': '#ffcc6655',
  'activityBar.dropBackground': dark #ffcc6655',01, // (1f),
  'activityBar.dropBorder': '#3399cc',
  'activityBar.foreground': '#c4bdb5ee',
  'activityBar.foreground': dark01, #c4bdb5ee',
  'activityBar.inactiveForeground': '#c4bdb5aa',
  'activityBar.inactiveForeground': dark01, // ( #c4bdb5aa',99),
  'activityBarBadge.background': '#3399cccc',
  'activityBarBadge.background': blue07,  '#3399cccc',
  'activityBarBadge.foreground': '#ffcc66cc',
  'activityBarBadge.foreground': dark01, #ffcc66cc',
  'badge.background': '#3399cccc',
  'badge.foreground': '#ffcc66cc',
  'badge.foreground': dark01, #ffcc66cc',
  'breadcrumb.activeSelectionForeground': '#c9bdb0dd',
  'breadcrumb.background': '#1d2547',
  'breadcrumb.background': dark20,  '#1d2547',
  'breadcrumb.focusForeground': '#d2c8bedd',
  'breadcrumb.foreground': '#d2c8beaa',
  'breadcrumb.foreground': dark06, // ( #d2c8beaa',cc),
  'breadcrumbPicker.background': '#2a255add',
  'breadcrumbPicker.background': dark19, #2a255add',
  'button.background': '#771166cc',
  'button.background': blue08,  '#771166cc',
  'button.foreground': '#c9bdb0ee',
  'button.foreground': dark01, #c9bdb0ee',
  'button.hoverBackground': '#3399cccc',
  'checkbox.background': dark14, #3399cccc',
  'checkbox.border': dark14, d': dark14,
  'checkbox.foreground': dar r': dark14,k02,
  'debugExceptionWidget.background': '#1d2555ee',
  'debugExceptionWidget.border': '#d2c8be33',
  'debugToolBar.background': '#2c203c',
  'debugToolBar.background': dark16,  '#2c203c',
  'debugToolBar.border': '#5522aa55',
  'diffEditor.border': '#77116600',
  'diffEditor.insertedTextBackground': '#88ddaa33',
  'diffEditor.insertedTextBorder': '#77116600',
  'diffEditor.removedTextBackground': '#ee447733',
  'diffEditor.removedTextBorder': '#77116600',
  'dropdown.background': '#1c1e2a',
  'dropdown.background': dark14,  '#1c1e2a',
  'dropdown.border': '#771166aa',
  'dropdown.border': dark14, #771166aa',
  'dropdown.foreground': '#d2c8bedd',
  'dropdown.foreground': dark02, #d2c8bedd',
  'dropdown.listBackground': '#19152f',
  'editor.background': '#20213b',
  'editor.background': dark20,  '#20213b',
  'editor.findMatchBackground': '#3399cc66',
  'editor.findMatchBorder': '#3333ffaa',
  'editor.findMatchHighlightBackground': '#3399cc44',
  'editor.findMatchHighlightBackground': orange02, // (55), '#3399cc44',
  'editor.findMatchHighlightBorder': '#3399ccaa',
  'editor.findRangeHighlightBackground': '#22335555',
  'editor.findRangeHighlightBackground': dark15, // ( #22335555',66),
  'editor.findRangeHighlightBorder': '#5522aa55',
  'editor.focusedStackFrameHighlightBackground': '#22335555',
  'editor.focusedStackFrameHighlightBackground': green01,  '#22335555',
  'editor.foldBackground': '#1155ee22',
  'editor.foreground': '#d2c8bedd',
  'editor.foreground': dark05, #d2c8bedd',
  'editor.hoverHighlightBackground': '#3399cc33',
  'editor.hoverHighlightBackground': blue04, // (40),  '#3399cc33',
  'editor.hoverHighlightBackground': red04, // (40),  '#3399cc33',
  'editor.inactiveSelectionBackground': '#3388dd77',
  'editor.inactiveSelectionBackground': dark15, #3388dd77',
  'editor.lineHighlightBackground': '#1155ee22',
  'editor.lineHighlightBorder': '#ee111122',
  'editor.rangeHighlightBackground': '#22335555',
  'editor.rangeHighlightBackground': dark01, // ( #22335555',0b),
  'editor.rangeHighlightBorder': '#77116611',
  'editor.selectionBackground': '#4422ee77',
  'editor.selectionBackground': blue04,  '#4422ee77',
  'editor.selectionBackground': red04,  '#4422ee77',
  'editor.selectionForeground': '#c9bdb0dd',
  'editor.selectionHighlightBackground': '#55227766',
  'editor.selectionHighlightBorder': '#5522aadd',
  'editor.snippetFinalTabstopHighlightBackground': '#22335599',
  'editor.snippetFinalTabstopHighlightBorder': '#223355aa',
  'editor.snippetTabstopHighlightBackground': '#22335577',
  'editor.snippetTabstopHighlightBorder': '#223355cc',
  'editor.stackFrameHighlightBackground': '#22335555',
  'editor.stackFrameHighlightBackground': yellow04, ': '#22335555',
  'editor.symbolHighlightBackground': '#4422ee77',
  'editor.symbolHighlightBorder': '#993366',
  'editor.wordHighlightBackground': '#88ddaa33',
  'editor.wordHighlightBorder': '#88ddaabb',
  'editor.wordHighlightStrongBackground': '#ee447733',
  'editor.wordHighlightStrongBorder': '#ee4477bb',
  'editorActiveLineNumber.foreground': dark07, #ee4477bb',
  'editorBracketMatch.background': '#aaee4444',
  'editorBracketMatch.background': green04,  '#aaee4444',
  'editorBracketMatch.border': '#aaee44bb',
  'editorCodeLens.foreground': '#d2c8be33',
  'editorCursor.background': '#22991155',
  'editorCursor.foreground': '#ff3333',
  'editorError.border': '#ff115544',
  'editorError.foreground': '#ff3366',
  'editorGroup.border': '#ffcc6655',
  'editorGroup.dropBackground': '#2c203c',
  'editorGroup.emptyBackground': '#1c1c2e',
  'editorGroup.focusedEmptyBorder': '#1c1c2e',
  'editorGroupHeader.border': '#001133',
  'editorGroupHeader.noTabsBackground': '#1c1c2e',
  'editorGroupHeader.noTabsBackground': dark20,  '#1c1c2e',
  'editorGroupHeader.tabsBackground': '#1c1c2e',
  'editorGroupHeader.tabsBackground': dark19,  '#1c1c2e',
  'editorGroupHeader.tabsBorder': '#1d2545',
  'editorGutter.addedBackground': '#88bb33',
  'editorGutter.addedBackground': green03, ': '#88bb33',
  'editorGutter.background': '#1d1c2f',
  'editorGutter.background': dark20,  '#1d1c2f',
  'editorGutter.commentRangeForeground': '#5533eeaa',
  'editorGutter.deletedBackground': '#bb3355',
  'editorGutter.foldingControlForeground': '#ffcc77cc',
  'editorGutter.modifiedBackground': '#3399cc',
  'editorHint.border': '#ffcc6644',
  'editorHint.foreground': '#ffcc55ee',
  'editorHoverWidget.background': '#1d2555ee',
  'editorHoverWidget.background': dark19, #1d2555ee',
  'editorHoverWidget.border': '#d2c8be55',
  'editorHoverWidget.border': dark13, #d2c8be55',
  'editorHoverWidget.foreground': '#c9bdb0dd',
  'editorHoverWidget.statusBarBackground': '#1c1c2e',
  'editorIndentGuide.activeBackground': '#44aaee33',
  'editorIndentGuide.background': '#44aaee11',
  'editorInfo.border': '#44aaee55',
  'editorInfo.foreground': '#c9bdb0dd',
  'editorInfo.foreground': blue01,  '#c9bdb0dd',
  'editorInfo.foreground': red01,  '#c9bdb0dd',
  'editorLightBulb.foreground': '#ffcc33dd',
  'editorLightBulbAutoFix.foreground': '#3399ccdd',
  'editorLightBulbAutoFix.foreground': red01,  '#3399ccdd',
  'editorLineNumber.activeForeground': '#d2c8bedd',
  'editorLineNumber.activeForeground': dark07, #d2c8bedd',
  'editorLineNumber.foreground': '#d2c8be55',
  'editorLink.activeForeground': '#d2c8bedd',
  'editorLink.activeForeground': green01,  '#d2c8bedd',
  'editorMarkerNavigation.background': '#223355',
  'editorMarkerNavigationError.background': '#bb3355bb',
  'editorMarkerNavigationInfo.background': '#ffcc55ee',
  'editorMarkerNavigationInfo.background': blue01,  '#ffcc55ee',
  'editorMarkerNavigationInfo.background': red01,  '#ffcc55ee',
  'editorMarkerNavigationWarning.background': '#d8cdb4bb',
  'editorMarkerNavigationWarning.background': yellow02, ': '#d8cdb4bb',
  'editorOverviewRuler.addedForeground': '#88bb33aa',
  'editorOverviewRuler.addedForeground': blue07, // (99),  '#88bb33aa',
  'editorOverviewRuler.border': '#3399cccc',
  'editorOverviewRuler.border': dark11, // ( #3399cccc',4d),
  'editorOverviewRuler.bracketMatchForeground': '#aaee44',
  'editorOverviewRuler.bracketMatchForeground': dark09,  '#aaee44',
  'editorOverviewRuler.commonContentForeground': '#88ddaaaa',
  'editorOverviewRuler.commonContentForeground': dark12, // ( #88ddaaaa',66),
  'editorOverviewRuler.currentContentForeground': '#3399ccaa',
  'editorOverviewRuler.deletedForeground': '#bb3355aa',
  'editorOverviewRuler.deletedForeground': blue07, // (99),  '#bb3355aa',
  'editorOverviewRuler.errorForeground': '#ff3366',
  'editorOverviewRuler.findMatchForeground': '#3399cc',
  'editorOverviewRuler.findMatchForeground': orange01, // (7e),': '#3399cc',
  'editorOverviewRuler.incomingContentForeground': '#dd2255ee',
  'editorOverviewRuler.incomingContentForeground': blue02, // (80),  '#dd2255ee',
  'editorOverviewRuler.incomingContentForeground': green02, // (80),  '#dd2255ee',
  'editorOverviewRuler.incomingContentForeground': red02, // (80), n02, // (80),
  'editorOverviewRuler.infoForeground': '#ffcc55ee',
  'editorOverviewRuler.infoForeground': blue01,  '#ffcc55ee',
  'editorOverviewRuler.infoForeground': red01,  '#ffcc55ee',
  'editorOverviewRuler.modifiedForeground': '#3399ccaa',
  'editorOverviewRuler.modifiedForeground': blue07, // (99),  '#3399ccaa',
  'editorOverviewRuler.rangeHighlightForeground': '#ff7733cc',
  'editorOverviewRuler.rangeHighlightForeground': blue07, // (99),  '#ff7733cc',
  'editorOverviewRuler.selectionHighlightForeground': '#ffcc55ee',
  'editorOverviewRuler.selectionHighlightForeground': dark09, // ( #ffcc55ee',cc),
  'editorOverviewRuler.warningForeground': '#ccff33',
  'editorOverviewRuler.warningForeground': yellow02, nd': '#ccff33',
  'editorOverviewRuler.wordHighlightForeground': '#88ddaa',
  'editorOverviewRuler.wordHighlightForeground': dark09, //  '#88ddaa', (cc),
  'editorOverviewRuler.wordHighlightStrongForeground': '#ee4477',
  'editorOverviewRuler.wordHighlightStrongForeground': purple01, ': '#ee4477',
  'editorPane.background': '#1c1c2e',
  'editorPane.background': dark20,  '#1c1c2e',
  'editorRuler.foreground': '#ee447744',
  'editorSuggestWidget.background': '#223355dd',
  'editorSuggestWidget.background': dark19, #223355dd',
  'editorSuggestWidget.border': '#66bbffdd',
  'editorSuggestWidget.border': dark13, #66bbffdd',
  'editorSuggestWidget.foreground': '#c4bdb5dd',
  'editorSuggestWidget.foreground': dark05, #c4bdb5dd',
  'editorSuggestWidget.highlightForeground': '#66bbffdd',
  'editorSuggestWidget.highlightForeground': blue06,  '#66bbffdd',
  'editorSuggestWidget.selectedBackground': '#44aaee44',
  'editorSuggestWidget.selectedBackground': blue10,  '#44aaee44',
  'editorUnnecessaryCode.border': '#9955bb44',
  'editorUnnecessaryCode.opacity': '#ffffff66',
  'editorUnnecessaryCode.opacity': dark21, // ( #ffffff66',aa),
  'editorWarning.border': '#eeaa2200',
  'editorWarning.foreground': '#ccff33',
  'editorWarning.foreground': yellow02, nd': '#ccff33',
  'editorWhitespace.foreground': '#d2c8be22',
  'editorWidget.background': '#1d2555ee',
  'editorWidget.background': dark19, #1d2555ee',
  'editorWidget.border': '#d2c8be55',
  'editorWidget.border': dark13, #d2c8be55',
  'editorWidget.foreground': '#c9bdb0dd',
  'editorWidget.foreground': dark06, #c9bdb0dd',
  'editorWidget.resizeBorder': '#3399ccee',
  'errorLens.errorBackground': '#ff336633',
  'errorLens.errorForeground': '#ff3366',
  'errorLens.errorMessageBackground': '#ff336666',
  'errorLens.hintBackground': '#3399cc33',
  'errorLens.hintForeground': '#3399cc',
  'errorLens.hintMessageBackground': '#3399cc66',
  'errorLens.infoBackground': '#ffbb0033',
  'errorLens.infoForeground': '#ffbb00',
  'errorLens.infoMessageBackground': '#ffbb0066',
  'errorLens.warningBackground': '#ccff3333',
  'errorLens.warningForeground': '#ccff33',
  'errorLens.warningMessageBackground': '#ccff3366',
  'extensionBadge.remoteBackground': '#771166cc',
  'extensionBadge.remoteBackground': blue07,  '#771166cc',
  'extensionBadge.remoteForeground': '#c9bdb0ee',
  'extensionBadge.remoteForeground': dark01, #c9bdb0ee',
  'extensionButton.prominentBackground': '#3399cc',
  'extensionButton.prominentBackground': green04, ': '#3399cc',
  'extensionButton.prominentForeground': '#ffeeccee',
  'extensionButton.prominentForeground': dark01, #ffeeccee',
  'extensionButton.prominentHoverBackground': '#771166cc',
  'extensionButton.prominentHoverBackground': green04,  '#771166cc',
  'gitDecoration.addedResourceForeground': '#33cc00dd',
  'gitDecoration.addedResourceForeground': green01,  '#33cc00dd',
  'gitDecoration.conflictingResourceForeground': '#ff2200dd',
  'gitDecoration.conflictingResourceForeground': purple01,  '#ff2200dd',
  'gitDecoration.deletedResourceForeground': '#993366',
  'gitDecoration.ignoredResourceForeground': '#0099ccdd',
  'gitDecoration.modifiedResourceForeground': '#ffbb00dd',
  'gitDecoration.modifiedResourceForeground': yellow01, ': '#ffbb00dd',
  'gitDecoration.submoduleResourceForeground': '#cc33ccdd',
  'gitDecoration.untrackedResourceForeground': '#ff9900dd',
  'gitDecoration.untrackedResourceForeground': green01,  '#ff9900dd',
  'icon.foreground': '#ffcc77cc',
  'imagePreview.border': '#c4bdb5',
  'imagePreview.border': dark10, //  '#c4bdb5', (59),
  'input.background': '#3399cc33',
  'input.background': dark14, #3399cc33',
  'input.border': '#eeaa2288',
  'input.foreground': '#ffeedddd',
  'input.foreground': dark06, #ffeedddd',
  'input.placeholderForeground': '#ffeedd88',
  'inputOption.activeBackground': '#77116688',
  'inputOption.activeBackground': blue08, // (66),  '#77116688',
  'inputOption.activeBorder': '#eeaa22bb',
  'inputOption.activeBorder': blue07, // (00),  '#eeaa22bb',
  'inputOption.activeForeground': '#c4bdb5',
  'inputValidation.errorBackground': '#77222233',
  'inputValidation.errorBorder': '#bb3355',
  'inputValidation.errorForeground': '#c9bdb0dd',
  'inputValidation.infoBackground': '#22335533',
  'inputValidation.infoBorder': '#ffcc55ee',
  'inputValidation.infoBorder': blue07,  '#ffcc55ee',
  'inputValidation.infoForeground': '#c9bdb0dd',
  'inputValidation.warningBackground': '#77552233',
  'inputValidation.warningBackground': yellow03, ': '#77552233',
  'inputValidation.warningBorder': '#ffcc55ee',
  'inputValidation.warningBorder': yellow03, ': '#ffcc55ee',
  'inputValidation.warningForeground': '#c9bdb0dd',
  'list.activeSelectionBackground': '#3399cc77',
  'list.activeSelectionBackground': blue09,  '#3399cc77',
  'list.activeSelectionForeground': dark01, d': blue09, und': blue09,
  'list.dropBackground': '#3399cc33',
  'list.errorForeground': '#ff3366',
  'list.filterMatchBackground': '#3399ccaa',
  'list.filterMatchBorder': '#ffcc33',
  'list.focusBackground': '#2222ee77',
  'list.focusBackground': blue10,  '#2222ee77',
  'list.focusForeground': '#ffffff',
  'list.highlightForeground': '#77bb55',
  'list.highlightForeground': blue06, ': '#77bb55',
  'list.hoverBackground': '#77116677',
  'list.hoverForeground': '#d2c8bedd',
  'list.inactiveFocusBackground': '#2222ee66',
  'list.inactiveSelectionBackground': '#3333dd77',
  'list.inactiveSelectionForeground': '#d2c8bedd',
  'list.invalidItemForeground': '#ff4422cc',
  'list.invalidItemForeground': yellow03, ': '#ff4422cc',
  'list.warningForeground': '#ccff33',
  'list.warningForeground': yellow02, nd': '#ccff33',
  'listFilterWidget.background': '#442266dd',
  'listFilterWidget.noMatchesOutline': '#442266dd',
  'listFilterWidget.outline': '#442266dd',
  'listFilterWidget.outline': dark21, // ( #442266dd',00),
  'menu.background': '#2c203c',
  'menu.background': dark19,  '#2c203c',
  'menu.border': '#77116611',
  'menu.foreground': '#d2c8bedd',
  'menu.foreground': dark06, #d2c8bedd',
  'menu.selectionBackground': '#eebb5555',
  'menu.selectionBackground': blue09,  '#eebb5555',
  'menu.selectionBorder': '#5522aadd',
  'menu.selectionForeground': '#c9bdb0dd',
  'menu.selectionForeground': dark01, #c9bdb0dd',
  'menu.separatorBackground': '#2c203c',
  'menu.separatorBackground': dark08,  '#2c203c',
  'menubar.selectionBackground': '#22995555',
  'menubar.selectionBackground': dark01, // ( #22995555',1a),
  'menubar.selectionBorder': '#66118866',
  'menubar.selectionForeground': '#c9bdb0dd',
  'menubar.selectionForeground': dark06, #c9bdb0dd',
  'merge.border': '#3399cccc',
  'merge.commonContentBackground': '#88ddaa33',
  'merge.commonContentBackground': dark12, // ( #88ddaa33',29),
  'merge.commonHeaderBackground': '#88ddaaaa',
  'merge.commonHeaderBackground': dark12, // ( #88ddaaaa',66),
  'merge.currentContentBackground': '#3399cc33',
  'merge.currentHeaderBackground': '#3399ccaa',
  'merge.incomingContentBackground': '#ee447733',
  'merge.incomingContentBackground': blue02, // (33),  '#ee447733',
  'merge.incomingContentBackground': green02, // (33),  '#ee447733',
  'merge.incomingHeaderBackground': '#dd2255ee',
  'merge.incomingHeaderBackground': blue02, // (80),  '#dd2255ee',
  'merge.incomingHeaderBackground': green02, // (80),  '#dd2255ee',
  'minimap.background': '#1d1c2f',
  'minimap.errorHighlight': '#ff3366',
  'minimap.findMatchHighlight': '#ff773388',
  'minimap.findMatchHighlight': orange01, '#ff773388',
  'minimap.selectionHighlight': '#88ddaa88',
  'minimap.selectionHighlight': red04,  '#88ddaa88',
  'minimap.warningHighlight': '#ccff33',
  'minimapGutter.addedBackground': '#88bb33cc',
  'minimapGutter.deletedBackground': '#bb3355cc',
  'minimapGutter.modifiedBackground': '#3399cccc',
  'minimapSlider.activeBackground': '#3399cccc',
  'minimapSlider.background': '#5522aa44',
  'minimapSlider.hoverBackground': '#5522aa88',
  'notificationCenter.border': '#77116611',
  'notificationCenterHeader.background': '#2c203c',
  'notificationCenterHeader.background': dark17,  '#2c203c',
  'notificationCenterHeader.foreground': '#d2c8bedd',
  'notificationLink.foreground': '#6699ffdd',
  'notificationLink.foreground': blue03,  '#6699ffdd',
  'notificationLink.foreground': red03,  '#6699ffdd',
  'notifications.background': '#1d1028',
  'notifications.background': dark19,  '#1d1028',
  'notifications.border': '#77116611',
  'notifications.border': dark17, #77116611',
  'notifications.foreground': '#c9bdb0dd',
  'notifications.foreground': dark06, #c9bdb0dd',
  'notificationsErrorIcon.foreground': '#ff3366',
  'notificationsInfoIcon.foreground': '#ffcc55',
  'notificationsInfoIcon.foreground': red01, ': '#ffcc55',
  'notificationsWarningIcon.foreground': '#ccff33',
  'notificationToast.border': '#77116611',
  'panel.background': '#201039',
  'panel.background': dark20,  '#201039',
  'panel.border': '#d2c8be55',
  'panel.border': dark10, // ( #d2c8be55',59),
  'panel.dropBackground': dark01,  0, // (59),// (1f),
  'panelInput.border': '#77116655',
  'panelTitle.activeBorder': '#3399cccc',
  'panelTitle.activeBorder': dark10, // ( #3399cccc',59),
  'panelTitle.activeForeground': '#d2c8bedd',
  'panelTitle.activeForeground': dark03, #d2c8bedd',
  'panelTitle.inactiveForeground': '#d2c8beaa',
  'panelTitle.inactiveForeground': dark03, // ( #d2c8beaa',99),
  'peekView.border': '#ffcc55ee',
  'peekView.border': blue07,  '#ffcc55ee',
  'peekViewEditor.background': '#223355bb',
  'peekViewEditor.background': blue11,  '#223355bb',
  'peekViewEditor.matchHighlightBackground': '#552266',
  'peekViewEditor.matchHighlightBackground': orange02,': '#552266',
  'peekViewEditor.matchHighlightBorder': '#661188',
  'peekViewEditorGutter.background': '#1d2545',
  'peekViewEditorGutter.background': blue11, ': '#1d2545',
  'peekViewResult.background': '#5522aa22',
  'peekViewResult.background': dark19, #5522aa22',
  'peekViewResult.fileForeground': '#c4bdb5dd',
  'peekViewResult.fileForeground': dark01, #c4bdb5dd',
  'peekViewResult.lineForeground': '#c4bdb5dd',
  'peekViewResult.lineForeground': dark08, #c4bdb5dd',
  'peekViewResult.matchHighlightBackground': '#3399cc55',
  'peekViewResult.matchHighlightBackground': orange02, // (4d), '#3399cc55',
  'peekViewResult.selectionBackground': '#4422bb44',
  'peekViewResult.selectionForeground': '#c4bdb5dd',
  'peekViewResult.selectionForeground': dark01, #c4bdb5dd',
  'peekViewTitle.background': '#1144bb55',
  'peekViewTitle.background': dark20, #1144bb55',
  'peekViewTitleDescription.foreground': '#c4bdb5dd',
  'peekViewTitleDescription.foreground': dark06, // ( #c4bdb5dd',b3),
  'peekViewTitleLabel.foreground': '#c4bdb5dd',
  'peekViewTitleLabel.foreground': dark01, #c4bdb5dd',
  'pickerGroup.border': '#77116611',
  'pickerGroup.foreground': '#d2c8bebb',
  'pickerGroup.foreground': blue03,  '#d2c8bebb',
  'pickerGroup.foreground': red03,  '#d2c8bebb',
  'problemsErrorIcon.foreground': '#ff3366',
  'problemsInfoIcon.foreground': '#ffcc55ee',
  'problemsWarningIcon.foreground': '#ccff33',
  'progressBar.background': '#3399cccc',
  'quickInput.background': dark19, #3399cccc',
  'quickInput.foreground': '#c4bdb5dd',
  'scrollbar.shadow': '#111122',
  'scrollbar.shadow': dark21,  '#111122',
  'scrollbarSlider.activeBackground': '#88bb33cc',
  'scrollbarSlider.background': '#3399cc99',
  'scrollbarSlider.hoverBackground': '#ffcc66cc',
  'searchEditor.findMatchBackground': '#99336655',
  'searchEditor.findMatchBorder': '#cc33ccaa',
  'selection.background': '#669988aa',
  'settings.checkboxBackground': '#3399cc44',
  'settings.checkboxBackground': dark14, #3399cc44',
  'settings.checkboxBorder': '#ffcc6677',
  'settings.checkboxBorder': dark14, #ffcc6677',
  'settings.checkboxForeground': '#d2c8bedd',
  'settings.checkboxForeground': dark02, #d2c8bedd',
  'settings.dropdownBackground': '#77116644',
  'settings.dropdownBackground': dark14, #77116644',
  'settings.dropdownBorder': '#ffcc6677',
  'settings.dropdownBorder': dark14, #ffcc6677',
  'settings.dropdownForeground': '#d2c8bedd',
  'settings.dropdownForeground': dark02, #d2c8bedd',
  'settings.dropdownListBorder': '#ffcc66bb',
  'settings.dropdownListBorder': dark13, #ffcc66bb',
  'settings.headerForeground': '#eeddcc',
  'settings.headerForeground': dark03,  '#eeddcc',
  'settings.modifiedItemIndicator': '#88bb33',
  'settings.numberInputBackground': '#3399cc44',
  'settings.numberInputBackground': dark18, #3399cc44',
  'settings.numberInputBorder': '#ffcc6644',
  'settings.numberInputForeground': '#d2c8bedd',
  'settings.numberInputForeground': dark06, #d2c8bedd',
  'settings.textInputBackground': '#77116644',
  'settings.textInputBackground': dark18, #77116644',
  'settings.textInputBorder': '#ffcc6644',
  'settings.textInputForeground': '#d2c8bedd',
  'settings.textInputForeground': dark06, #d2c8bedd',
  'sideBar.background': '#1d1028',
  'sideBar.background': dark19,  '#1d1028',
  'sideBar.border': '#ffcc3377',
  'sideBar.dropBackground': '#77449933',
  'sideBar.dropBackground': dark01, // ( #77449933',1f),
  'sideBar.foreground': '#d2c8bedd',
  'sideBarSectionHeader.background': '#77116666',
  'sideBarSectionHeader.background': dark10, // ( #77116666',33),
  'sideBarSectionHeader.border': '#ffbbaa55',
  'sideBarSectionHeader.foreground': '#d2c8bedd',
  'sideBarTitle.foreground': '#d2c8bedd',
  'sideBarTitle.foreground': dark08, #d2c8bedd',
  'statusBar.background': '#1d2547',
  'statusBar.background': blue07, ': '#1d2547',
  'statusBar.border': '#77116600',
  'statusBar.debuggingBackground': '#cc6600',
  'statusBar.debuggingBackground': orange01,': '#cc6600',
  'statusBar.debuggingBorder': '#77116600',
  'statusBar.debuggingForeground': '#d2c8bedd',
  'statusBar.debuggingForeground': dark01, #d2c8bedd',
  'statusBar.foreground': '#d2c8beaa',
  'statusBar.foreground': dark01, #d2c8beaa',
  'statusBar.noFolderBackground': '#884488',
  'statusBar.noFolderBackground': purple03, ': '#884488',
  'statusBar.noFolderBorder': '#77116600',
  'statusBar.noFolderForeground': '#d2c8bedd',
  'statusBar.noFolderForeground': dark01, #d2c8bedd',
  'statusBarItem.activeBackground': '#1c1c2e',
  'statusBarItem.activeBackground': dark01, //  '#1c1c2e', (2e),
  'statusBarItem.hoverBackground': '#1c1c2e',
  'statusBarItem.hoverBackground': dark01, //  '#1c1c2e', (1f),
  'statusBarItem.prominentBackground': '#669944',
  'statusBarItem.prominentBackground': dark21, //  '#669944', (80),
  'statusBarItem.prominentForeground': '#d2c8bedd',
  'statusBarItem.prominentForeground': dark01, #d2c8bedd',
  'statusBarItem.prominentHoverBackground': '#1c1c2e',
  'statusBarItem.prominentHoverBackground': dark21, //  '#1c1c2e', (4d),
  'statusBarItem.remoteBackground': green03, c1c2e', (4d),
  'statusBarItem.remoteForeground': dark01, ': green03, nd': green03,
  'symbolIcon.arrayForeground': '#77cc22',
  'symbolIcon.booleanForeground': '#77cc22',
  'symbolIcon.classForeground': '#dd8811',
  'symbolIcon.colorForeground': '#c4bdb5dd',
  'symbolIcon.constantForeground': '#297dc4',
  'symbolIcon.constructorForeground': '#ee11aaee',
  'symbolIcon.enumeratorForeground': '#ffbb22',
  'symbolIcon.enumeratorMemberForeground': '#66bbffdd',
  'symbolIcon.eventForeground': '#ffcc33ee',
  'symbolIcon.fieldForeground': '#3399ccdd',
  'symbolIcon.fileForeground': '#c4bdb5dd',
  'symbolIcon.folderForeground': '#c4bdb5dd',
  'symbolIcon.functionForeground': '#ffcc33ee',
  'symbolIcon.interfaceForeground': '#297dc4',
  'symbolIcon.keyForeground': '#c4bdb5dd',
  'symbolIcon.keywordForeground': '#dd2255',
  'symbolIcon.methodForeground': '#aa55bbee',
  'symbolIcon.moduleForeground': '#aa55bbee',
  'symbolIcon.namespaceForeground': '#c4bdb5dd',
  'symbolIcon.nullForeground': '#aa55bb',
  'symbolIcon.numberForeground': '#ee6677',
  'symbolIcon.objectForeground': '#77cc22',
  'symbolIcon.operatorForeground': '#66bbffdd',
  'symbolIcon.packageForeground': '#ff9900',
  'symbolIcon.propertyForeground': '#3399cc',
  'symbolIcon.referenceForeground': '#00539c',
  'symbolIcon.snippetForeground': '#652d90',
  'symbolIcon.stringForeground': '#ccee55',
  'symbolIcon.structForeground': '#66bbffdd',
  'symbolIcon.textForeground': '#ffcc33',
  'symbolIcon.typeParameterForeground': '#c4bdb5dd',
  'symbolIcon.unitForeground': '#44bb99',
  'symbolIcon.variableForeground': '#66bbff',
  'tab.activeBackground': '#1d2545',
  'tab.activeBackground': dark20,  '#1d2545',
  'tab.activeBorder': '#1d254500',
  'tab.activeBorderTop': '#ccff33',
  'tab.activeForeground': '#d2c8bedd',
  'tab.activeForeground': dark01, #d2c8bedd',
  'tab.activeModifiedBorder': '#ff3366',
  'tab.activeModifiedBorder': blue05, ': '#ff3366',
  'tab.border': '#1c1c2e',
  'tab.border': dark19,  '#1c1c2e',
  'tab.hoverBackground': '#5522aa55',
  'tab.hoverBorder': '#3399cc',
  'tab.hoverForeground': '#d2c8be',
  'tab.inactiveBackground': '#2a2040',
  'tab.inactiveForeground': '#d2c8beaa',
  'tab.inactiveForeground': dark01, // ( #d2c8beaa',80),
  'tab.inactiveModifiedBorder': '#ff445599',
  'tab.inactiveModifiedBorder': blue05, // (80),  '#ff445599',
  'tab.unfocusedActiveBackground': '#1d2545',
  'tab.unfocusedActiveBackground': dark20,  '#1d2545',
  'tab.unfocusedActiveBorder': '#1d254500',
  'tab.unfocusedActiveBorderTop': '#aaee4499',
  'tab.unfocusedActiveForeground': '#d2c8bedd',
  'tab.unfocusedActiveForeground': dark01, // ( #d2c8bedd',80),
  'tab.unfocusedActiveModifiedBorder': '#ff445599',
  'tab.unfocusedActiveModifiedBorder': blue05, // (80),  '#ff445599',
  'tab.unfocusedHoverBackground': '#5522aa44',
  'tab.unfocusedHoverBorder': '#3399ccdd',
  'tab.unfocusedHoverForeground': '#d2c8be',
  'tab.unfocusedInactiveBackground': '#2a2040',
  'tab.unfocusedInactiveForeground': '#d2c8beaa',
  'tab.unfocusedInactiveForeground': dark01, // ( #d2c8beaa',40),
  'tab.unfocusedInactiveModifiedBorder': '#ff445555',
  'tab.unfocusedInactiveModifiedBorder': blue05, // (40),  '#ff445555',
  'terminal.ansiBlack': '#201020',
  'terminal.ansiBlack': dark21,  '#201020',
  'terminal.ansiBlue': '#458588',
  'terminal.ansiBrightBlack': '#928374',
  'terminal.ansiBrightBlue': '#99c6ca',
  'terminal.ansiBrightCyan': '#8ae180',
  'terminal.ansiBrightGreen': '#b5c033',
  'terminal.ansiBrightGreen': green02, ': '#b5c033',
  'terminal.ansiBrightMagenta': '#d66282',
  'terminal.ansiBrightMagenta': purple02, ': '#d66282',
  'terminal.ansiBrightRed': '#f42c3e',
  'terminal.ansiBrightWhite': '#ddccaa',
  'terminal.ansiBrightWhite': dark04,  '#ddccaa',
  'terminal.ansiBrightYellow': '#fabe2f',
  'terminal.ansiBrightYellow': yellow04, ow': '#fabe2f',
  'terminal.ansiCyan': '#689e6a',
  'terminal.ansiGreen': '#98971a',
  'terminal.ansiMagenta': '#b16286',
  'terminal.ansiMagenta': purple02, ': '#b16286',
  'terminal.ansiRed': '#cc241d',
  'terminal.ansiWhite': '#c0b0a0',
  'terminal.ansiWhite': dark04,  '#c0b0a0',
  'terminal.ansiYellow': '#e7a931',
  'terminal.ansiYellow': yellow04, ow': '#e7a931',
  'terminal.background': '#202010',
  'terminal.background': dark20,  '#202010',
  'terminal.border': '#77116655',
  'terminal.border': dark10, // ( #77116655',59),
  'terminal.foreground': '#c4bdb5dd',
  'terminal.foreground': dark06, #c4bdb5dd',
  'terminal.selectionBackground': '#33227777',
  'terminal.selectionBackground': dark01, // ( #33227777',40),
  'terminalCursor.background': '#29153a',
  'terminalCursor.foreground': '#ff3333',
  'textBlockQuote.background': '#2c203c',
  'textBlockQuote.background': dark11, //  '#2c203c', (1a),
  'textBlockQuote.border': '#77116611',
  'textBlockQuote.border': blue07, // (80),  '#77116611',
  'textCodeBlock.background': '#2c203c',
  'textLink.activeForeground': '#6644ccdd',
  'textLink.activeForeground': blue03,  '#6644ccdd',
  'textLink.activeForeground': red03,  '#6644ccdd',
  'textLink.foreground': '#6699ffdd',
  'textLink.foreground': blue03,  '#6699ffdd',
  'textLink.foreground': red03,  '#6699ffdd',
  'textPreformat.foreground': '#d2c8bedd',
  'textPreformat.foreground': yellow01, ': '#d2c8bedd',
  'textSeparator.foreground': '#d2c8bedd',
  'textSeparator.foreground': dark01, // ( #d2c8bedd',2e),
  'titleBar.activeBackground': '#1c1c2e',
  'titleBar.activeBackground': dark14,  '#1c1c2e',
  'titleBar.activeForeground': '#d2c8bedd',
  'titleBar.activeForeground': dark06, #d2c8bedd',
  'titleBar.border': '#1c1c2e',
  'titleBar.inactiveBackground': '#1c1c2e',
  'titleBar.inactiveBackground': dark14, //  '#1c1c2e', (99),
  'titleBar.inactiveForeground': '#d2c8beaa',
  'titleBar.inactiveForeground': dark06, // ( #d2c8beaa',99),
  'walkThrough.embeddedEditorBackground': '#2c203c',
  'welcomePage.background': '#1d1028',
  'welcomePage.buttonBackground': '#771166cc',
  'welcomePage.buttonHoverBackground': '#3399cccc',
  'widget.shadow': '#001111',
  'widget.shadow': dark21,  '#001111',
  'window.activeBorder': '#771166aa',
  'window.inactiveBorder': '#1b1b26',
  contrastActiveBorder: '#ff115500',
  contrastBorder: '#d2c8be44',
  descriptionForeground: '#c9bdb0ee',
  descriptionForeground: dark06, // (b3),
  errorForeground: '#d2c8bebb',
  focusBorder: '#771166aa',
  focusBorder: blue08, // (cc),
  foreground: '#d2c8bedd',
  foreground: dark05,
  foreground: dark06,
  incomingContentBackground: red02, // (33),
  incomingHeaderBackground: red02, // (80),

*/
